package mullvad

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

type Token struct {
	AccessToken string    `json:"access_token"`
	Expiry      time.Time `json:"expiry"`
}

type Devices []struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Pubkey      string        `json:"pubkey"`
	HijackDNS   bool          `json:"hijack_dns"`
	Created     time.Time     `json:"created"`
	Ipv4Address string        `json:"ipv4_address"`
	Ipv6Address string        `json:"ipv6_address"`
	Ports       []interface{} `json:"ports"`
}

type Device struct {
	ID          string        `json:"id"`
	Name        string        `json:"name"`
	Pubkey      string        `json:"pubkey"`
	HijackDNS   bool          `json:"hijack_dns"`
	Created     time.Time     `json:"created"`
	Ipv4Address string        `json:"ipv4_address"`
	Ipv6Address string        `json:"ipv6_address"`
	Ports       []interface{} `json:"ports"`
}
// will be our api interaction for mullvad
var myClient = &http.Client{Timeout: 10 * time.Second}

func GetToken(accountNumber string) Token {
	client := &http.Client{
		Timeout: time.Second * 10,
	}

	url := "https://api.mullvad.net/auth/v1/token"
	method := "POST"
	postdata := strings.NewReader(`{"account_number":"` + accountNumber + `"}`)

	req, err := http.NewRequest(method, url, postdata)
	if err != nil {
		fmt.Println("Error creating request:", err)
		return Token{}
	}
	// Set header
	req.Header.Add("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println("Error making request:", err)
		return Token{}
	}
	defer resp.Body.Close()

	// Read and print response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Println("Error reading response body:", err)
		return Token{}
	}
	fmt.Println(string(body))

	var unmarshaledToken Token
	json.Unmarshal(body, &unmarshaledToken)

	return unmarshaledToken
}

func GetRelays(token Token) AutoGenerated {
	client := &http.Client{
		Timeout: time.Second * 10,
	}
	url := "https://api.mullvad.net/app/v1/relays"
	method := "GET"
	getdata := strings.NewReader(`{"access_token":"` + token.AccessToken + `"}`)

	req, err := http.NewRequest(method, url, getdata)
	if err != nil {
		fmt.Println("Error creating request:", err)
		return AutoGenerated{}
	}
	// Set header
	req.Header.Add("Content-Type", "application/json")
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println("Error making request:", err)
		return AutoGenerated{}
	}
	defer resp.Body.Close()

	// Read and print response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Println("Error reading response body:", err)
		return AutoGenerated{}
	}
	//fmt.Println(string(body))

	var unmarshaledRelays AutoGenerated
	json.Unmarshal(body, &unmarshaledRelays)

	return unmarshaledRelays
}

func AddKey(token Token, pubKey string) (int, error) {
	client := &http.Client{
		Timeout: time.Second * 10,
	}

	formData := url.Values{}
	formData.Set("key", pubKey)

	req, err := http.NewRequest("POST", "https://mullvad.net/en/account/devices?/upload-key", strings.NewReader(formData.Encode()))
	if err != nil {
		return 0, err
	}

	req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Add("Accept", "application/json")
	req.Header.Add("Referer", "https://mullvad.net/en/account/devices")
	req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Add("Accept", "application/json")
	req.Header.Add("Accept-Language", "en-GB,en;q=0.9")
	req.Header.Add("Referer", "https://mullvad.net/en/account/devices")
	req.Header.Add("Origin", "https://mullvad.net")
	req.Header.Add("x-sveltekit-action", "true")
	req.Header.Add("User-Agent", "Go")
	req.AddCookie(&http.Cookie{
		Name:  "accessToken",
		Value: token.AccessToken,
	})

	resp, err := client.Do(req)
	if err != nil {
		return 0, err
	}
	defer resp.Body.Close()

	return resp.StatusCode, nil
}

func GetDevices(token Token) Devices {
	var allDevices Devices

	client := &http.Client{
		Timeout: time.Second * 10,
	}
	getdata := strings.NewReader(`{"access_token":"` + token.AccessToken + `"}`)
	req, err := http.NewRequest("GET", "https://api.mullvad.net/accounts/v1/devices", getdata)
	if err != nil {
		return allDevices
	}

	authtoken := "Bearer " + token.AccessToken
	req.Header.Add("Authorization", authtoken)
	req.Header.Add("Accept", "application/json")

	// Set header
	resp, err := client.Do(req)
	if err != nil {
		fmt.Println("Error making request:", err)
		return allDevices
	}
	defer resp.Body.Close()

	// Read and print response
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Println("Error reading response body:", err)
		return allDevices
	}
	//fmt.Println(string(body))
	json.Unmarshal(body, &allDevices)

	return allDevices
}

// Get a device by the public key associated to it
func GetDevicebyPubkey(deviceList Devices, pubkey string) Device {
	for i := 0; i<len(deviceList); i++ {
		if deviceList[i].Pubkey == pubkey {
			return deviceList[i]
		}
	}
	return Device{}
}

// Get a device by the internal id used by the api
func GetDevicebyId(deviceList Devices, id string) Device {
	for i := 0; i<len(deviceList); i++ {
		if deviceList[i].ID == id {
			return deviceList[i]
		}
	}
	return Device{}
}

// Get a device by searching the human readeable name e.g: agile boa
func GetDevicebyName(deviceList Devices, name string) Device {
	for i := 0; i<len(deviceList); i++ {
		if deviceList[i].Name == name {
			return deviceList[i]
		}
	}
	return Device{}
}

func RemoveDevice(token Token, id string) (int, error) {
	client := &http.Client{
		Timeout: time.Second * 10,
	}

	formData := url.Values{}
	formData.Set("id", id)

	req, err := http.NewRequest("POST", "https://mullvad.net/en/account/devices?/revoke-device", strings.NewReader(formData.Encode()))
	if err != nil {
		return 0, err
	}

	req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Add("Accept", "application/json")
	req.Header.Add("Referer", "https://mullvad.net/en/account/devices")
	req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Add("Accept", "application/json")
	req.Header.Add("Accept-Language", "en-GB,en;q=0.9")
	req.Header.Add("Referer", "https://mullvad.net/en/account/devices")
	req.Header.Add("Origin", "https://mullvad.net")
	req.Header.Add("x-sveltekit-action", "true")
	req.Header.Add("User-Agent", "Go")
	req.AddCookie(&http.Cookie{
		Name:  "accessToken",
		Value: token.AccessToken,
	})

	resp, err := client.Do(req)
	if err != nil {
		return 0, err
	}
	defer resp.Body.Close()

	return resp.StatusCode, nil
}
